# -*- coding: utf-8 -*-
"""data-analysis-of-books-data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UVGypHCG25dpW8FWuzXz6MIQ8-ud4Rgx

**I welcome all the feedbacks and suggestions to improve my working on data analysis and scraping ! ♥**
"""

import pandas as pd
import seaborn as sns

df = pd.read_csv('books_data.csv')

df.sample(6)

df['Tax'].unique() #basically 0 tax hehe when we gotta get those days back! :p

df['stock'] = df['Availability'].apply(lambda x: x.split('(')[1][:2])

df.sample(6)

df['stock'].unique()

sns.countplot(x=df['stock'])
plt.xlabel("Stock")
plt.ylabel("Count")
plt.title("Stock Counts")

"""Looks like majority of them got their few copies sold and ended up at 14-16 copies in the stock! Not so sure how much were present. Number of copies in the stock actually provides a deep insight regarding the book itself, the more famous a book is, the lesser copies are left for the book."""

df['price_for_hist'] = df['Price'].apply(lambda x: float(x[2:]))

df.sample(5)

plt.hist(df['price_for_hist'], bins=10, edgecolor='black')
plt.xlabel('Price (in Â£)') # can't really predict any probability distribution for prior posterior working,
# as the data suggests its not based on any real data so yeah hehe!

!pip install wordcloud matplotlib pandas

import matplotlib.pyplot as plt
from wordcloud import WordCloud

text = " ".join(title for title in df["Title"])

wordcloud = WordCloud(width=800, height=400, background_color="white", colormap="viridis").generate(text)
plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation="bilinear")
plt.axis("off")
plt.title("WordCloud of Book Titles!", fontsize=14)
plt.show() # the most beautiful part of this code!!
